// This file was automatically generated by the Dapper.SimpleCRUD T4 Template
// Do not make changes directly to this file - edit the template instead
// 
// The following connection settings were used to generate this file
// 
//     Connection String Name: `authconnect`
//     Provider:               `System.Data.SqlClient`
//     Connection String:      `Data Source=.;Initial Catalog=Apiauthorisation;Integrated Security=True`
//     Include Views:          `True`

using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Collections.Generic;

namespace BANKSOFRI_LOAN.DATALAYER.Models
{
    /// <summary>
    /// A class which represents the NanoLoanRepaymentSchedule table.
    /// </summary>
	[Table("NanoLoanRepaymentSchedule")]
	public partial class NanoLoanRepaymentSchedule
	{
		[Key]
		public virtual int Id { get; set; }
		public virtual DateTime Date { get; set; }
		public virtual string LoanReferenceId { get; set; }
		public virtual DateTime RepaymentDate { get; set; }
		public virtual decimal PrincipalDue { get; set; }
		public virtual decimal InterestDue { get; set; }
		public virtual int DaysOverDue { get; set; }
		public virtual string Status { get; set; }
	}

    /// <summary>
    /// A class which represents the DailyBillsPayments table.
    /// </summary>
	[Table("DailyBillsPayments")]
	public partial class DailyBillsPayment
	{
		[Key]
		public virtual int Id { get; set; }
		public virtual DateTime Date { get; set; }
		public virtual string AccountNumber { get; set; }
		public virtual string Narration { get; set; }
		public virtual decimal Amount { get; set; }
	}

    /// <summary>
    /// A class which represents the BankCodes table.
    /// </summary>
	[Table("BankCodes")]
	public partial class BankCode
	{
		[Key]
		public virtual int Id { get; set; }
		public virtual string Code { get; set; }
		public virtual string Name { get; set; }
		public virtual string Status { get; set; }
	}

    /// <summary>
    /// A class which represents the NanoLoans table.
    /// </summary>
	[Table("NanoLoans")]
	public partial class NanoLoan
	{
		[Key]
		public virtual int Id { get; set; }
		public virtual DateTime Date { get; set; }
		public virtual string LoanReferenceId { get; set; }
		public virtual string CustomerID { get; set; }
		public virtual string CustomerName { get; set; }
		public virtual string Email { get; set; }
		public virtual string SofriAccountNumber { get; set; }
		public virtual int Tenure { get; set; }
		public virtual decimal LoanAmount { get; set; }
		public virtual decimal InterestRate { get; set; }
		public virtual decimal InterestAmount { get; set; }
		public virtual decimal TotalPayable { get; set; }
		public virtual DateTime RepaymentStartDate { get; set; }
		public virtual decimal LoanBalance { get; set; }
		public virtual DateTime RepaymentEndDate { get; set; }
		public virtual string Status { get; set; }
		public virtual string Remark { get; set; }
		public virtual string NextRepaymentDate { get; set; }
		public virtual bool IsOverDue { get; set; }
		public virtual string PhoneNumber { get; set; }
		public virtual string BankOneReferenceId { get; set; }
	}

    /// <summary>
    /// A class which represents the __EFMigrationsHistory table.
    /// </summary>
	[Table("__EFMigrationsHistory")]
	public partial class EFMigrationsHistory
	{
		[Key]
		public virtual string MigrationId { get; set; }
		public virtual string ProductVersion { get; set; }
	}

    /// <summary>
    /// A class which represents the CreditRiskAssessment table.
    /// </summary>
	[Table("CreditRiskAssessment")]
	public partial class CreditRiskAssessment
	{
		[Key]
		public virtual int Id { get; set; }
		public virtual string RiskItem { get; set; }
		public virtual string Options { get; set; }
		public virtual decimal Score { get; set; }
	}

    /// <summary>
    /// A class which represents the RiskAssessmentScore table.
    /// </summary>
	[Table("RiskAssessmentScore")]
	public partial class RiskAssessmentScore
	{
		[Key]
		public virtual int Id { get; set; }
		public virtual DateTime Date { get; set; }
		public virtual string CustomerID { get; set; }
		public virtual string CustomerName { get; set; }
		public virtual string RiskItem { get; set; }
		public virtual decimal AssessmentScore { get; set; }
		public virtual decimal WeightedAvgScore { get; set; }
	}

    /// <summary>
    /// A class which represents the AvgScoreSetup table.
    /// </summary>
	[Table("AvgScoreSetup")]
	public partial class AvgScoreSetup
	{
		[Key]
		public virtual int Id { get; set; }
		public virtual string RiskName { get; set; }
		public virtual decimal WeightAvg { get; set; }
	}

    /// <summary>
    /// A class which represents the PndRecords table.
    /// </summary>
	[Table("PndRecords")]
	public partial class PndRecord
	{
		[Key]
		public virtual int Id { get; set; }
		public virtual DateTime Date { get; set; }
		public virtual string CustomerId { get; set; }
		public virtual string AccountNumber { get; set; }
		public virtual string AuthCode { get; set; }
		public virtual string Status { get; set; }
	}

    /// <summary>
    /// A class which represents the BankMapping table.
    /// </summary>
	[Table("BankMapping")]
	public partial class BankMapping
	{
		[Key]
		public virtual int Id { get; set; }
		public virtual string Institution_code { get; set; }
		public virtual string Institution_name { get; set; }
		public virtual int Category { get; set; }
		public virtual string B_ONE_CODE { get; set; }
		public virtual string B_ONE_NAME { get; set; }
	}

    /// <summary>
    /// A class which represents the CreditScoreData table.
    /// </summary>
	[Table("CreditScoreData")]
	public partial class CreditScoreData
	{
		[Key]
		public virtual int Id { get; set; }
		public virtual DateTime Date { get; set; }
		public virtual string CustomerId { get; set; }
		public virtual string Bureau { get; set; }
		public virtual string ScoreData { get; set; }
	}

    /// <summary>
    /// A class which represents the CustomerBVNData table.
    /// </summary>
	[Table("CustomerBVNData")]
	public partial class CustomerBVNData
	{
		[Key]
		public virtual int Id { get; set; }
		public virtual DateTime Date { get; set; }
		public virtual string CustomerId { get; set; }
		public virtual string bvn { get; set; }
		public virtual string firstname { get; set; }
		public virtual string lastname { get; set; }
		public virtual string middlename { get; set; }
		public virtual string phone { get; set; }
		public virtual string gender { get; set; }
		public virtual string birthdate { get; set; }
		public virtual string photo { get; set; }
		public virtual string maritalStatus { get; set; }
		public virtual string lgaOfResidence { get; set; }
		public virtual string lgaOfOrigin { get; set; }
		public virtual string residentialAddress { get; set; }
		public virtual string stateOfOrigin { get; set; }
		public virtual string enrollmentBank { get; set; }
		public virtual string enrollmentBranch { get; set; }
		public virtual string nameOnCard { get; set; }
		public virtual string title { get; set; }
		public virtual string levelOfAccount { get; set; }
	}

    /// <summary>
    /// A class which represents the CustomerDetails table.
    /// </summary>
	[Table("CustomerDetails")]
	public partial class CustomerDetail
	{
		[Key]
		public virtual int Id { get; set; }
		public virtual string CustomerId { get; set; }
		public virtual string FirstName { get; set; }
		public virtual string LastName { get; set; }
		public virtual string MaritalStatus { get; set; }
		public virtual string Gender { get; set; }
		public virtual string DateOfBirth { get; set; }
		public virtual string Street { get; set; }
		public virtual string City { get; set; }
		public virtual string State { get; set; }
		public virtual string PostalCode { get; set; }
		public virtual string Country { get; set; }
		public virtual string Email { get; set; }
		public virtual string Phone { get; set; }
		public virtual string KYC_score { get; set; }
		public virtual string BVN { get; set; }
		public virtual string EmployerName { get; set; }
		public virtual string Industry { get; set; }
		public virtual int EmploymentDuration { get; set; }
		public virtual decimal Income { get; set; }
		public virtual string Type { get; set; }
		public virtual bool IncomeVerified { get; set; }
		public virtual string LevelOfEducation { get; set; }
		public virtual string ResidenceStatus { get; set; }
		public virtual string EmploymentType { get; set; }
		public virtual decimal LoanAmount { get; set; }
		public virtual string LoanPurpose { get; set; }
	}

    /// <summary>
    /// A class which represents the TestBVNRecords table.
    /// </summary>
	[Table("TestBVNRecords")]
	public partial class TestBVNRecord
	{
		[Key]
		public virtual int Id { get; set; }
		public virtual string BVN { get; set; }
		public virtual string Name { get; set; }
		public virtual string Phone { get; set; }
		public virtual string DOB { get; set; }
		public virtual string Gender { get; set; }
	}

    /// <summary>
    /// A class which represents the Logs table.
    /// </summary>
	[Table("Logs")]
	public partial class Log
	{
		[Key]
		public virtual int Id { get; set; }
		public virtual DateTime LogTime { get; set; }
		public virtual string Type { get; set; }
		public virtual string Details { get; set; }
	}

    /// <summary>
    /// A class which represents the Schema table.
    /// </summary>
	[Table("Schema")]
	public partial class Schema
	{
		[Key]
		public virtual int Version { get; set; }
	}

    /// <summary>
    /// A class which represents the UserAuthentication table.
    /// </summary>
	[Table("UserAuthentication")]
	public partial class UserAuthentication
	{
		[Key]
		public virtual int Id { get; set; }
		public virtual string UserEmail { get; set; }
		public virtual string UserId { get; set; }
		public virtual string TokenCode { get; set; }
		public virtual DateTime TimeIssued { get; set; }
		public virtual string Status { get; set; }
		public virtual DateTime? TimeUsed { get; set; }
		public virtual DateTime? ExpirationTime { get; set; }
	}

    /// <summary>
    /// A class which represents the Job table.
    /// </summary>
	[Table("Job")]
	public partial class Job
	{
		[Key]
		public virtual int Id { get; set; }
		public virtual int? StateId { get; set; }
		public virtual string StateName { get; set; }
		public virtual string InvocationData { get; set; }
		public virtual string Arguments { get; set; }
		public virtual DateTime CreatedAt { get; set; }
		public virtual DateTime? ExpireAt { get; set; }
	}

    /// <summary>
    /// A class which represents the State table.
    /// </summary>
	[Table("State")]
	public partial class State
	{
		[Key]
		public virtual int Id { get; set; }
		public virtual int JobId { get; set; }
		public virtual string Name { get; set; }
		public virtual string Reason { get; set; }
		public virtual DateTime CreatedAt { get; set; }
		public virtual string Data { get; set; }
	}

    /// <summary>
    /// A class which represents the Authorised table.
    /// </summary>
	[Table("Authorised")]
	public partial class Authorised
	{
		[Key]
		public virtual int Id { get; set; }
		public virtual DateTime Date { get; set; }
		public virtual string UserName { get; set; }
		public virtual string AppId { get; set; }
		public virtual string AppKey { get; set; }
	}

    /// <summary>
    /// A class which represents the JobParameter table.
    /// </summary>
	[Table("JobParameter")]
	public partial class JobParameter
	{
		[Key]
		public virtual int Id { get; set; }
		public virtual int JobId { get; set; }
		public virtual string Name { get; set; }
		public virtual string Value { get; set; }
	}

    /// <summary>
    /// A class which represents the JobQueue table.
    /// </summary>
	[Table("JobQueue")]
	public partial class JobQueue
	{
		[Key]
		public virtual int Id { get; set; }
		public virtual int JobId { get; set; }
		public virtual string Queue { get; set; }
		public virtual DateTime? FetchedAt { get; set; }
	}

    /// <summary>
    /// A class which represents the OnboardingIssues table.
    /// </summary>
	[Table("OnboardingIssues")]
	public partial class OnboardingIssue
	{
		[Key]
		public virtual int Id { get; set; }
		public virtual DateTime Date { get; set; }
		public virtual string CustomerId { get; set; }
		public virtual string PhoneNumber { get; set; }
		public virtual string AccountNumber { get; set; }
		public virtual string IssueDetails { get; set; }
	}

    /// <summary>
    /// A class which represents the Server table.
    /// </summary>
	[Table("Server")]
	public partial class Server
	{
		[Key]
		public virtual string Id { get; set; }
		public virtual string Data { get; set; }
		public virtual DateTime LastHeartbeat { get; set; }
	}

    /// <summary>
    /// A class which represents the CustomersTable table.
    /// </summary>
	[Table("CustomersTable")]
	public partial class CustomersTable
	{
		[Key]
		public virtual int Id { get; set; }
		public virtual string FirstName { get; set; }
		public virtual string LastName { get; set; }
		public virtual string Email { get; set; }
		public virtual string PhoneNumber { get; set; }
		public virtual string Password { get; set; }
		public virtual DateTime DateCreated { get; set; }
	}

    /// <summary>
    /// A class which represents the List table.
    /// </summary>
	[Table("List")]
	public partial class List
	{
		[Key]
		public virtual int Id { get; set; }
		public virtual string Key { get; set; }
		public virtual string Value { get; set; }
		public virtual DateTime? ExpireAt { get; set; }
	}

    /// <summary>
    /// A class which represents the Set table.
    /// </summary>
	[Table("Set")]
	public partial class Set
	{
		[Key]
		public virtual int Id { get; set; }
		public virtual string Key { get; set; }
		public virtual double Score { get; set; }
		public virtual string Value { get; set; }
		public virtual DateTime? ExpireAt { get; set; }
	}

    /// <summary>
    /// A class which represents the Counter table.
    /// </summary>
	[Table("Counter")]
	public partial class Counter
	{
		[Key]
		public virtual int Id { get; set; }
		public virtual string Key { get; set; }
		public virtual short Value { get; set; }
		public virtual DateTime? ExpireAt { get; set; }
	}

    /// <summary>
    /// A class which represents the Hash table.
    /// </summary>
	[Table("Hash")]
	public partial class Hash
	{
		[Key]
		public virtual int Id { get; set; }
		public virtual string Key { get; set; }
		public virtual string Field { get; set; }
		public virtual string Value { get; set; }
		public virtual DateTime? ExpireAt { get; set; }
	}

    /// <summary>
    /// A class which represents the AggregatedCounter table.
    /// </summary>
	[Table("AggregatedCounter")]
	public partial class AggregatedCounter
	{
		[Key]
		public virtual int Id { get; set; }
		public virtual string Key { get; set; }
		public virtual long Value { get; set; }
		public virtual DateTime? ExpireAt { get; set; }
	}

    /// <summary>
    /// A class which represents the CreditBureauResults table.
    /// </summary>
	[Table("CreditBureauResults")]
	public partial class CreditBureauResult
	{
		[Key]
		public virtual int Id { get; set; }
		public virtual DateTime Date { get; set; }
		public virtual string CustomerId { get; set; }
		public virtual string CreditBureauDetails { get; set; }
		public virtual int CreditScore { get; set; }
		public virtual string CreditRemark { get; set; }
	}

    /// <summary>
    /// A class which represents the LoanProcessingData table.
    /// </summary>
	[Table("LoanProcessingData")]
	public partial class LoanProcessingData
	{
		[Key]
		public virtual int Id { get; set; }
		public virtual DateTime Date { get; set; }
		public virtual string CustomerId { get; set; }
		public virtual string Offers { get; set; }
		public virtual string ApplicationId { get; set; }
		public virtual string Guid { get; set; }
		public virtual string OverallDecision { get; set; }
		public virtual string DeclineReasons { get; set; }
		public virtual string Errors { get; set; }
		public virtual string ApplicationXML { get; set; }
		public virtual string RequestId { get; set; }
		public virtual string OfferStatus { get; set; }
		public virtual string EmploymentType { get; set; }
		public virtual string RiskLevel { get; set; }
	}

    /// <summary>
    /// A class which represents the CustomerAccounts table.
    /// </summary>
	[Table("CustomerAccounts")]
	public partial class CustomerAccount
	{
		[Key]
		public virtual int Id { get; set; }
		public virtual DateTime? Date { get; set; }
		public virtual string CustomerId { get; set; }
		public virtual string UserId { get; set; }
		public virtual string FirstName { get; set; }
		public virtual string LastName { get; set; }
		public virtual string OtherNames { get; set; }
		public virtual string PhoneNumber { get; set; }
		public virtual string Email { get; set; }
		public virtual DateTime? DOB { get; set; }
		public virtual string AccountNumber { get; set; }
		public virtual string BVN { get; set; }
		public virtual string homeAddress { get; set; }
		public virtual string city { get; set; }
		public virtual string state { get; set; }
		public virtual string lga { get; set; }
		public virtual string image { get; set; }
		public virtual string signature { get; set; }
		public virtual string imageType { get; set; }
		public virtual string signatureType { get; set; }
		public virtual string identificationImage { get; set; }
		public virtual string identificationType { get; set; }
		public virtual string DocumentType { get; set; }
		public virtual string DocumentFrontPath { get; set; }
		public virtual string DocumentBackPath { get; set; }
		public virtual string LivelinessVideoPath { get; set; }
		public virtual string MattiVerificationId { get; set; }
		public virtual string IdentityVerificationStatus { get; set; }
		public virtual string AccountUpgradeStatus { get; set; }
		public virtual string GeneralStatus { get; set; }
		public virtual DateTime? UpdatedAt { get; set; }
	}

    /// <summary>
    /// A class which represents the ProvenirDecisionData table.
    /// </summary>
	[Table("ProvenirDecisionData")]
	public partial class ProvenirDecisionData
	{
		[Key]
		public virtual int Id { get; set; }
		public virtual DateTime Date { get; set; }
		public virtual string CustomerId { get; set; }
		public virtual string ReferenceID { get; set; }
		public virtual string LoanData { get; set; }
		public virtual string Status { get; set; }
	}

    /// <summary>
    /// A class which represents the PaystackBanks table.
    /// </summary>
	[Table("PaystackBanks")]
	public partial class PaystackBank
	{
		[Key]
		public virtual int Id { get; set; }
		public virtual string Code { get; set; }
		public virtual string Name { get; set; }
	}

    /// <summary>
    /// A class which represents the Defaulters table.
    /// </summary>
	[Table("Defaulters")]
	public partial class Defaulter
	{
		[Key]
		public virtual int Id { get; set; }
		public virtual string CustomerId { get; set; }
		public virtual string CustomerName { get; set; }
		public virtual string AccountNumber { get; set; }
		public virtual DateTime Date { get; set; }
	}

    /// <summary>
    /// A class which represents the NanoLoanRequests table.
    /// </summary>
	[Table("NanoLoanRequests")]
	public partial class NanoLoanRequest
	{
		[Key]
		public virtual int Id { get; set; }
		public virtual DateTime Date { get; set; }
		public virtual string CustomerID { get; set; }
		public virtual string FirstName { get; set; }
		public virtual string LastName { get; set; }
		public virtual string Gender { get; set; }
		public virtual string PhoneNumber { get; set; }
		public virtual string Email { get; set; }
		public virtual string EmploymentType { get; set; }
		public virtual decimal Income { get; set; }
		public virtual decimal LoanAmount { get; set; }
	}

    /// <summary>
    /// A class which represents the CustomerOffers table.
    /// </summary>
	[Table("CustomerOffers")]
	public partial class CustomerOffer
	{
		[Key]
		public virtual int Id { get; set; }
		public virtual DateTime Date { get; set; }
		public virtual string CustomerId { get; set; }
		public virtual string Offers { get; set; }
		public virtual string Status { get; set; }
	}

    /// <summary>
    /// A class which represents the MonoAccounts table.
    /// </summary>
	[Table("MonoAccounts")]
	public partial class MonoAccount
	{
		[Key]
		public virtual int Id { get; set; }
		public virtual DateTime Date { get; set; }
		public virtual string CustomerId { get; set; }
		public virtual string MonoAccountId { get; set; }
	}

    /// <summary>
    /// A class which represents the LienHistory table.
    /// </summary>
	[Table("LienHistory")]
	public partial class LienHistory
	{
		[Key]
		public virtual int Id { get; set; }
		public virtual DateTime Date { get; set; }
		public virtual string CustomerId { get; set; }
		public virtual string AccountNumber { get; set; }
		public virtual decimal LienAmount { get; set; }
		public virtual string LoanReferenceId { get; set; }
		public virtual string LienReferenceId { get; set; }
		public virtual DateTime RemoveDate { get; set; }
		public virtual string LienStatus { get; set; }
	}

    /// <summary>
    /// A class which represents the SofriOtherLoanCustomers table.
    /// </summary>
	[Table("SofriOtherLoanCustomers")]
	public partial class SofriOtherLoanCustomer
	{
		[Key]
		public virtual int Id { get; set; }
		public virtual string CustomerId { get; set; }
		public virtual string FirstName { get; set; }
		public virtual string LastName { get; set; }
		public virtual string PhoneNumber { get; set; }
		public virtual string Email { get; set; }
		public virtual decimal loanRepaymentAmount { get; set; }
		public virtual string SofriAccountNumber { get; set; }
		public virtual string LoanId { get; set; }
	}

    /// <summary>
    /// A class which represents the PromoCodeUsers table.
    /// </summary>
	[Table("PromoCodeUsers")]
	public partial class PromoCodeUser
	{
		[Key]
		public virtual int Id { get; set; }
		public virtual DateTime Date { get; set; }
		public virtual string CustomerId { get; set; }
		public virtual string AccountNumber { get; set; }
		public virtual string PromoCode { get; set; }
	}

    /// <summary>
    /// A class which represents the SofriPromo table.
    /// </summary>
	[Table("SofriPromo")]
	public partial class SofriPromo
	{
		[Key]
		public virtual int Id { get; set; }
		public virtual DateTime Date { get; set; }
		public virtual string PromoCode { get; set; }
		public virtual string CodeType { get; set; }
		public virtual DateTime StartDate { get; set; }
		public virtual string Description { get; set; }
		public virtual decimal AmountValue { get; set; }
		public virtual DateTime Expiration { get; set; }
		public virtual string UsedBy { get; set; }
		public virtual string DateUsed { get; set; }
		public virtual int? TotalUsers { get; set; }
		public virtual int? TotalUsed { get; set; }
		public virtual int? balance { get; set; }
		public virtual string Indentifier { get; set; }
		public virtual string Status { get; set; }
		public virtual string PromoOwnerCustomerId { get; set; }
		public virtual string PromoOwnerAccountNumber { get; set; }
	}

    /// <summary>
    /// A class which represents the Rates table.
    /// </summary>
	[Table("Rates")]
	public partial class Rate
	{
		[Key]
		public virtual int Id { get; set; }
		public virtual string EmploymentStatus { get; set; }
		public virtual string RiskLevel { get; set; }
		public virtual int? Tenor { get; set; }
		public virtual decimal? BasisPoint { get; set; }
		public virtual decimal? InterestRate { get; set; }
	}

    /// <summary>
    /// A class which represents the ServiceLogs table.
    /// </summary>
	[Table("ServiceLogs")]
	public partial class ServiceLog
	{
		[Key]
		public virtual int Id { get; set; }
		public virtual DateTime LogTime { get; set; }
		public virtual string Type { get; set; }
		public virtual string Details { get; set; }
	}

    /// <summary>
    /// A class which represents the OtherLoans table.
    /// </summary>
	[Table("OtherLoans")]
	public partial class OtherLoan
	{
		[Key]
		public virtual int Id { get; set; }
		public virtual DateTime Date { get; set; }
		public virtual string CustomerId { get; set; }
		public virtual string CustomerName { get; set; }
		public virtual string BVN { get; set; }
		public virtual string PhoneNumber { get; set; }
		public virtual string Email { get; set; }
		public virtual decimal LoanAmount { get; set; }
		public virtual string LoanPurpose { get; set; }
		public virtual string LoanType { get; set; }
	}

    /// <summary>
    /// A class which represents the AddressVerificationDetails table.
    /// </summary>
	[Table("AddressVerificationDetails")]
	public partial class AddressVerificationDetail
	{
		[Key]
		public virtual int Id { get; set; }
		public virtual string firstname { get; set; }
		public virtual string lastname { get; set; }
		public virtual string phone { get; set; }
		public virtual string middlename { get; set; }
		public virtual string gender { get; set; }
		public virtual DateTime? birthdate { get; set; }
		public virtual string lattitude { get; set; }
		public virtual string longitude { get; set; }
		public virtual string city { get; set; }
		public virtual string street { get; set; }
		public virtual string lga { get; set; }
		public virtual string state { get; set; }
		public virtual string country { get; set; }
		public virtual string reference { get; set; }
		public virtual string status { get; set; }
	}

    /// <summary>
    /// A class which represents the VerificationRequest table.
    /// </summary>
	[Table("VerificationRequest")]
	public partial class VerificationRequest
	{
		[Key]
		public virtual int Id { get; set; }
		public virtual DateTime? Date { get; set; }
		public virtual string street { get; set; }
		public virtual string lga { get; set; }
		public virtual string state { get; set; }
		public virtual string landmark { get; set; }
		public virtual string idType { get; set; }
		public virtual string idNumber { get; set; }
		public virtual string firstname { get; set; }
		public virtual string lastname { get; set; }
		public virtual string phone { get; set; }
		public virtual string dob { get; set; }
		public virtual string VerificationStatus { get; set; }
	}

    /// <summary>
    /// A class which represents the Reversals table.
    /// </summary>
	[Table("Reversals")]
	public partial class Reversal
	{
		[Key]
		public virtual int Id { get; set; }
		public virtual string RetrievalReference { get; set; }
		public virtual DateTime TransactionDate { get; set; }
		public virtual string TransactionType { get; set; }
		public virtual decimal Amount { get; set; }
		public virtual string Status { get; set; }
		public virtual DateTime RetrialTime { get; set; }
	}

    /// <summary>
    /// A class which represents the TransactionDetails table.
    /// </summary>
	[Table("TransactionDetails")]
	public partial class TransactionDetail
	{
		[Key]
		public virtual int Id { get; set; }
		public virtual DateTime? date { get; set; }
		public virtual string TransactionType { get; set; }
		public virtual string custNo { get; set; }
		public virtual string sourceAccount { get; set; }
		public virtual string destinationAccountNo { get; set; }
		public virtual decimal amount { get; set; }
		public virtual string narration { get; set; }
		public virtual string referenceNo { get; set; }
		public virtual string destinationBankCode { get; set; }
		public virtual string sourceAccountName { get; set; }
		public virtual string destinationAccountName { get; set; }
		public virtual string lookupReference { get; set; }
		public virtual string currencyCode { get; set; }
	}

    /// <summary>
    /// A class which represents the NanoLoanRepayment table.
    /// </summary>
	[Table("NanoLoanRepayment")]
	public partial class NanoLoanRepayment
	{
		[Key]
		public virtual int Id { get; set; }
		public virtual DateTime Date { get; set; }
		public virtual string LoanReferenceId { get; set; }
		public virtual decimal LoanBalance { get; set; }
		public virtual decimal AmountPaid { get; set; }
		public virtual decimal NewBalance { get; set; }
		public virtual decimal? RepaymentDiscountRate { get; set; }
		public virtual decimal? RepaymentDiscountAmount { get; set; }
		public virtual string RepaymentReference { get; set; }
		public virtual string Remark { get; set; }
	}

}
